version: "3.7"
services:
  mongodb:
    image: "mongo"
    container_name: mongodb_setup
    env_file:
      - database.env # configure mongodb
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database:/data/db
    restart: unless-stopped
    ports:
      - 27017:27017
volumes:
    database: