version: "3.7"
services:
  # database image
  database:
    container_name: mysql_local
    image: "mysql:latest" # use latest official mysql version
    env_file:
      - database.env # configure mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql # persist data even if container shuts down

volumes:
  database: # named volumes can be managed easier using docker-compose
